/**
 * Toasty - A GitHub App that responds to /plan commands
 * 
 * This app listens for issue comments containing the /plan command
 * and responds with a code plan for the issue.
 * 
 * @param {import('probot').Probot} app
 */

module.exports = (app) => {
  app.log.info("Toasty app is running!");

  // Listen for issue comments
  app.on("issue_comment.created", async (context) => {
    const comment = context.payload.comment.body;
    const issueNumber = context.payload.issue.number;
    
    // Check if the comment contains the /plan command
    if (comment.trim().startsWith("/plan")) {
      app.log.info(`Received /plan command on issue #${issueNumber}`);
      
      // Get issue details
      const issue = context.payload.issue;
      const issueTitle = issue.title;
      const issueBody = issue.body || "No description provided";
      
      // Generate a plan based on the issue
      const plan = generatePlan(issueTitle, issueBody);
      
      // Post the plan as a comment
      const response = await context.octokit.issues.createComment(
        context.issue({
          body: plan
        })
      );
      
      app.log.info(`Posted plan on issue #${issueNumber}`);
      return response;
    }
  });
};

/**
 * Generate a code plan based on the issue title and description
 * 
 * @param {string} title - The issue title
 * @param {string} body - The issue body/description
 * @returns {string} The generated plan
 */
function generatePlan(title, body) {
  const plan = `## 📋 Code Plan

**Issue:** ${title}

### Analysis
${body}

### Proposed Implementation Plan

1. **Understand Requirements**
   - Review the issue description and requirements
   - Identify key components and dependencies
   - Clarify any ambiguities

2. **Design Solution**
   - Break down the problem into smaller tasks
   - Identify files that need to be created or modified
   - Plan the architecture and approach

3. **Implementation Steps**
   - Set up necessary configuration files
   - Implement core functionality
   - Add error handling and edge cases
   - Write tests for new functionality

4. **Testing & Validation**
   - Run unit tests
   - Perform integration testing
   - Validate against requirements
   - Test edge cases

5. **Documentation**
   - Update relevant documentation
   - Add code comments where necessary
   - Update README if needed

6. **Review & Refine**
   - Code review
   - Address feedback
   - Refactor if necessary

---
*This plan was generated by Toasty 🍞. Feel free to modify it based on your specific needs!*`;

  return plan;
}
